# Generated by Django 6.0.2 on 2026-03-24 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='缺陷標題')),
                ('description', models.TextField(verbose_name='缺陷描述')),
                ('reporter_email', models.EmailField(max_length=254, verbose_name='回報者 Email')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='嚴重程度')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='優先級')),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('assigned', 'Assigned'), ('fixed', 'Fixed'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='狀態')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='回報時間')),
                ('date_fixed', models.DateTimeField(blank=True, null=True, verbose_name='修復時間')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='指派給')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
            },
        ),
    ]
