# Generated by Django 6.0.2 on 2026-04-03 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='Product ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to=settings.AUTH_USER_MODEL, verbose_name='Product Owner')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='Steps to Reproduce')),
                ('tester_id', models.CharField(max_length=100, verbose_name='Tester ID')),
                ('reporter_email', models.EmailField(max_length=254, verbose_name='Reporter Email')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('assigned', 'Assigned'), ('fixed', 'Fixed'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='Status')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Received')),
                ('date_fixed', models.DateTimeField(blank=True, null=True, verbose_name='Fixed Date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='defects.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Defect',
                'verbose_name_plural': 'Defects',
            },
        ),
    ]
