# Generated by Django 6.0.2 on 2026-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('fixed', 'Fixed'), ('reopened', 'Reopened'), ('resolved', 'Resolved'), ('duplicate', 'Duplicate'), ('cannot_reproduce', 'Canot_Reproduce')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Product ID'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_id', 'version')},
        ),
    ]
