# Generated by Django 6.0.2 on 2026-03-25 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'verbose_name': 'Defect', 'verbose_name_plural': 'Defects'},
        ),
        migrations.AlterField(
            model_name='defect',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_fixed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fixed Date'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reported Date'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='description',
            field=models.TextField(verbose_name='Defect Description'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='reporter_email',
            field=models.EmailField(max_length=254, verbose_name='Reporter Email'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('assigned', 'Assigned'), ('fixed', 'Fixed'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Defect Title'),
        ),
    ]
