# Generated by Django 6.0.2 on 2026-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
        ),
    ]
