# Generated by Django 6.0.2 on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_defecthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='duplicate_of',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplicate_children',
                to='defects.defect',
            ),
        ),
    ]